### ISSUE TITLE
it's not working

### ISSUE THREAD

**Issue by th0ughts** [DavidRomanovizc/DatingBot#52]
i did the instruction step-by-step and still some error appears to me
i already set the IP

```
Traceback (most recent call last):
  File "/home/venv/DatingBot/django_app.py", line 3, in <module>
    main()
  File "/home/venv/DatingBot/django_project/telegrambot/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/venv/django-venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/venv/django-venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/home/venv/django-venv/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/venv/django-venv/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/venv/django-venv/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/venv/DatingBot/django_project/telegrambot/telegrambot/settings.py", line 18, in <module>
    from data import config
  File "/home/venv/DatingBot/data/config.py", line 11, in <module>
    IP = env.str("ip")
  File "/home/venv/django-venv/lib/python3.9/site-packages/environs/__init__.py", line 75, in method
    raise EnvValidationError('Environment variable "{}" not set'.format(source_key), [message])
environs.EnvValidationError: Environment variable "ip" not set
```

**Comment by vR4eslav** [comment]
thx, now it's working
