### ISSUE TITLE
Exception Value: relation "usersmanage_user" does not exist

### ISSUE THREAD

**Issue by Keksov** [DavidRomanovizc/DatingBot#70]
I've got the error message after fresh install.
```
Exception Type: ProgrammingError at /admin/usersmanage/user/
Exception Value: relation "usersmanage_user" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "
```
My database has the following tables
![image](https://user-images.githubusercontent.com/2372440/230757029-d89bacad-f31f-4ed2-9c59-1cce34086731.png)
 
Did I miss some importatnt step probably? 

```
Environment:

Request Method: GET
Request URL: http://localhost:8000/admin/usersmanage/user/

Django Version: 4.1.4
Python Version: 3.10.11
Installed Applications:
['jazzmin',
 'django_project.telegrambot.usersmanage',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/dodo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)

The above exception (relation "usersmanage_user" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "usersmanage_user"
                                          ^
) was the direct cause of the following exception:
  File "/home/dodo/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dodo/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dodo/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/dodo/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/dodo/.local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/dodo/.local/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/dodo/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/dodo/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/dodo/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1931, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/dodo/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 834, in get_changelist_instance
    return ChangeList(
  File "/home/dodo/.local/lib/python3.10/site-packages/django/contrib/admin/views/main.py", line 123, in __init__
    self.get_results(request)
  File "/home/dodo/.local/lib/python3.10/site-packages/django/contrib/admin/views/main.py", line 279, in get_results
    result_count = paginator.count
  File "/home/dodo/.local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/dodo/.local/lib/python3.10/site-packages/django/core/paginator.py", line 96, in count
    return c()
  File "/home/dodo/.local/lib/python3.10/site-packages/django/db/models/query.py", line 621, in count
    return self.query.get_count(using=self.db)
  File "/home/dodo/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 559, in get_count
    return obj.get_aggregation(using, ["__count"])["__count"]
  File "/home/dodo/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 544, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/dodo/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/home/dodo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/home/dodo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/dodo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/dodo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/dodo/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/dodo/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /admin/usersmanage/user/
Exception Value: relation "usersmanage_user" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "usersmanage_user"
                                          ^
```

**Comment by DavidRomanovizc** [comment]
Hello Perhaps the problem is related to the fact that the table was not created in the database. To do this, you can execute the command `python django_app.py makemigrations usersmanage` to create the necessary migrations, and then execute the command `python django_app.py migrate usersmanage` to apply the migrations.

**Comment by Keksov** [comment]
Thank you! Fixed. I'm new to django framework...
